name: Build Windows Pico2

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    with:
      os: windows-latest
      board: pico2